export const SHOW_DATA_LIST = 'SHOW_DATA_LIST'
export const SHOW_DATA_LIST_FULFILLED = 'SHOW_DATA_LIST_FULFILLED'
export const SHOW_DATA_LIST_REJECTED = 'SHOW_DATA_LIST_REJECTED'
export const SEARCH_DATA_LIST = 'SEARCH_DATA_LIST'